//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoTransportes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Viaje()
        {
            this.Gastos_Viaje = new HashSet<Gastos_Viaje>();
        }
    
        public byte ViajeID { get; set; }
        public string SerialNumber { get; set; }
        public string EmployeeID { get; set; }
        public byte RutaID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Camione Camione { get; set; }
        public virtual Conductore Conductore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gastos_Viaje> Gastos_Viaje { get; set; }
        public virtual Ruta Ruta { get; set; }
    }
}
